version: '3.8'

services:

  be-app:
    container_name: share-resume-be
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile-BE
    environment:
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB=${DB}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}"
      - "JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}"
      - "JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}"
      - "JWT_REFRESH_TOKEN_EXPIRATION_DAYS=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}"
      - "COMPANIES_INTEGRATOR_URL=${COMPANIES_INTEGRATOR_URL}"
      - "COMPANIES_INTEGRATOR_TOKEN=${COMPANIES_INTEGRATOR_TOKEN}"
      - "TEST_COMPANIES_INTEGRATOR_TOKEN=${TEST_COMPANIES_INTEGRATOR_TOKEN}"
      - "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
      - "MINIO_URL=${MINIO_URL}"
      - "ANONYMIZER_INTEGRATOR_URL=${ANONYMIZER_INTEGRATOR_URL}"
      - "ANONYMIZER_INTEGRATOR_TOKEN=${ANONYMIZER_INTEGRATOR_TOKEN}"
      - "COMPANIES_INTEGRATOR_SIZE_PARAMETER=${COMPANIES_INTEGRATOR_SIZE_PARAMETER}"
      - "SERVER_HOST=${SERVER_HOST}"
    depends_on:
      - db
      - minio
      - anon-app

  anon-app:
    container_name: share-resume-anon-app
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile-ANON
    environment:
      - "API_KEY=${ANONYMIZER_INTEGRATOR_TOKEN}"
      - "PYTHONPATH=/app/src"
      - "PORT=8000"
      - "DEBUG=0"

  db:
    container_name: share-resume-db
    image: postgres:17
    ports:
      - "${DOCKER_EXPOSE_DB_PORT}:5432"
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB}"
    volumes:
      - database_vol:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB}" ]
      interval: 1s
      timeout: 10s
      retries: 15

  minio:
    image: quay.io/minio/minio
    container_name: share-resume-minio
    environment:
      - "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
      - "MINIO_CONSOLE_ADDRESS=:9001"
    ports:
      - "${DOCKER_EXPOSE_MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile-FE
    ports:
      - '${DOCKER_NGINX_EXPOSE_PORT}:80'
    depends_on:
      - be-app

volumes:
  minio_data:
  database_vol: